#!/usr/bin/env python3
"""Sinh sdk/mtk/shelltypes_mtk.h: kiểu SHELL của mọi tham số ghi được mà
common_set_value_check_param() (functions/common/common) kiểm theo kiểu.

Vì sao cần bảng riêng: kiểu trong bảng DMLEAF của C không nói được điều
shell đã làm.  Shell chỉ kiểm đúng sáu chuỗi (phân biệt hoa thường):
xsd:unsignedInt, xsd:int, xsd:boolean, xsd:dateTime, xsd:IPv4Address,
xsd:IPv6Address.  "xsd:Int", "xsd:unsignedint", "" rơi vào nhánh *) -- không
kiểm gì -- trong khi C ghi chúng là DMT_INT / DMT_UNINT / DMT_STRING; còn
IPv4Address/IPv6Address thì C ghi DMT_STRING nhưng shell có kiểm.

Dùng:
    ./gen-shell-types.py > <overlay>/public/libs/libicwmp_dm/src/sdk/mtk/shelltypes_mtk.h

Đường dẫn chuẩn hoá như verify-dm-paths.py: $N và mọi segment toàn chữ số
thành {i}.  Dòng còn biến chưa bung ({v}) bị bỏ: không khớp được path nào.

TR-181 (branch dev_181): tên TR-181 của cùng tham số, theo tr181_mapping.tsv,
mang cùng kiểu, để SPV qua Device.* bị kiểm như qua InternetGatewayDevice.*.
Chỉ loại A/C (cùng giá trị); loại B đổi cách viết giá trị, setter TR-181 của
nó tự dịch và kiểm.
"""
import importlib.util
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
MATRIX = os.path.join(HERE, "tr098_coverage_matrix.tsv")
RULES = os.path.join(HERE, "tr181_mapping.tsv")
CHECKED = ("xsd:unsignedInt", "xsd:int", "xsd:boolean", "xsd:dateTime",
           "xsd:IPv4Address", "xsd:IPv6Address")

INSTANCE_RE = re.compile(r"\$\d+")
NUM_SEG_RE = re.compile(r"(?<=\.)\d+(?=\.|$)")


def norm(path):
    return NUM_SEG_RE.sub("{i}", INSTANCE_RE.sub("{i}", path))


def main():
    data = open(MATRIX, "rb").read()
    rows = []
    for line in data.decode("utf-8").splitlines()[1:]:
        c = line.split("\t")
        if len(c) < 8 or c[2] != "param" or c[4] != "1" or c[7] not in CHECKED:
            continue
        p = norm(c[3])
        if "{v}" in p or "$" in p:
            continue
        rows.append((p, c[7]))
    spec = importlib.util.spec_from_file_location("tr181map", os.path.join(HERE, "tr181-map.py"))
    tm = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(tm)
    rules, n181 = tm.load_rules(), 0
    for p, t in list(rows):
        r, m = tm.find(rules, p)
        if not r or r[3] not in ("A", "C"):
            continue
        t181 = tm.target(r, m, p)
        if t181:
            rows.append((tm.pat(t181), t))
            n181 += 1
    rows = sorted(set(rows))
    out = sys.stdout
    out.write("/*\n * GENERATED by docs/issue/gen-shell-types.py\n"
              " * from tr098_coverage_matrix.tsv (sha256 %s)\n"
              " * and tr181_mapping.tsv (sha256 %s).  Do not edit.\n"
              " *\n * The shell type of every writable parameter that\n"
              " * common_set_value_check_param() checks by type -- see\n"
              " * input_contract_mtk.c -- and of its TR-181 name (types A/C\n"
              " * of the mapping).  %d rows, %d of them TR-181.\n */\n"
              % (hashlib.sha256(data).hexdigest()[:16],
                 hashlib.sha256(open(RULES, "rb").read()).hexdigest()[:16], len(rows), n181))
    out.write("#ifndef __SHELLTYPES_MTK_H\n#define __SHELLTYPES_MTK_H\n\n")
    out.write("static const struct mtk_shell_type {\n\tconst char *path;\n"
              "\tconst char *type;\n} mtk_shell_types[] = {\n")
    for p, t in rows:
        out.write('\t{ "%s", "%s" },\n' % (p, t))
    out.write("\t{ NULL, NULL }\n};\n\n#endif\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
