# GENERATED by tools/sdk-scan.sh -- do not edit.
# Included from bin/Makefile.am; each fragment guards itself with its
# own AM_CONDITIONAL, so only the selected SDK contributes sources.

include $(top_srcdir)/sdk/bdk/sdk.mk
include $(top_srcdir)/sdk/mtk/sdk.mk
include $(top_srcdir)/sdk/uci/sdk.mk
