#!/bin/sh
# Rebuild sdk/enabled.m4 and sdk/enabled.mk from the directories that exist
# under sdk/.  Run it after adding or deleting an SDK, then autoreconf.
#
#   ./tools/sdk-scan.sh [--check]
#
# --check exits non-zero when the generated files are out of date (use it in
# CI, or before shipping a pruned tree).
#
# An SDK directory is any sdk/<name>/ that has both sdk.m4 and sdk.mk.
set -e

cd "$(dirname "$0")/.."
check=0
[ "$1" = "--check" ] && check=1

sdks=
for d in sdk/*/; do
	n=${d#sdk/}
	n=${n%/}
	[ -f "sdk/$n/sdk.m4" ] || continue
	[ -f "sdk/$n/sdk.mk" ] || continue
	sdks="$sdks $n"
done
sdks=$(echo $sdks)
[ -n "$sdks" ] || { echo "sdk-scan: no SDK under sdk/" >&2; exit 1; }

default=uci
case " $sdks " in
	*" uci "*) default=uci ;;
	*)         default=$(echo "$sdks" | awk '{print $1}') ;;
esac

gen_m4() {
	cat <<M4EOF
# GENERATED by tools/sdk-scan.sh -- do not edit.
# One entry per directory under sdk/ that carries sdk.m4 and sdk.mk.
# m4_included by configure.ac, which knows no SDK name at all.

m4_define([SDK_LIST], [$sdks])
m4_define([SDK_DEFAULT], [$default])

# with_sdk co the da duoc configure.ac dat truoc (alias cu): khong xoa no
AC_ARG_WITH([sdk],
  [AS_HELP_STRING([--with-sdk=NAME], [SDK backend, one of: $sdks (default $default)])],
  [with_sdk=\$withval], [])
# --with-platform is the name this option had before the sdk/ layout; kept so
# existing build scripts (BDK Makefile, OpenWrt feed) keep working.
AC_ARG_WITH([platform],
  [AS_HELP_STRING([--with-platform=NAME], [deprecated alias of --with-sdk])],
  [test -z "\$with_sdk" && with_sdk=\$withval], [])
AS_IF([test -z "\$with_sdk"], [with_sdk=$default])
AC_MSG_CHECKING([SDK backend])
AC_MSG_RESULT([\$with_sdk])
SDK_NAME=\$with_sdk
AC_SUBST([SDK_NAME])

# Every fragment is included unconditionally and guards itself on \$with_sdk:
# an AM_CONDITIONAL must be reached on every configure run or config.status
# refuses to substitute it.
M4EOF
	for n in $sdks; do
		echo "m4_include([sdk/$n/sdk.m4])"
	done
	echo
	echo "AS_CASE([\$with_sdk],"
	for n in $sdks; do
		echo "  [$n], [],"
	done
	echo "  [AC_MSG_ERROR([unknown --with-sdk=\$with_sdk, this tree has: $sdks])])"
}

gen_mk() {
	echo "# GENERATED by tools/sdk-scan.sh -- do not edit."
	echo "# Included from bin/Makefile.am; each fragment guards itself with its"
	echo "# own AM_CONDITIONAL, so only the selected SDK contributes sources."
	echo
	for n in $sdks; do
		echo "include \$(top_srcdir)/sdk/$n/sdk.mk"
	done
}

if [ "$check" = 1 ]; then
	rc=0
	gen_m4 | cmp -s - sdk/enabled.m4 || { echo "sdk/enabled.m4 is stale" >&2; rc=1; }
	gen_mk | cmp -s - sdk/enabled.mk || { echo "sdk/enabled.mk is stale" >&2; rc=1; }
	exit $rc
fi

gen_m4 > sdk/enabled.m4
gen_mk > sdk/enabled.mk
echo "sdk-scan: SDKs =$sdks (default $default)"
