#!/bin/sh
# Regenerate sdk/mtk/dm098/tz_table_mtk.h from the product's easycwmp
# function library, so Time.LocalTimeZoneName accepts exactly the cities the
# old client accepted.
#
#   ./tools/gen-tz-table.sh <2025q3>/tclinux_phoenix/apps/hni/cwmpclient/ext/openwrt/scripts/functions/tr098/time \
#       > sdk/mtk/dm098/tz_table_mtk.h
#
# Verify afterwards: the row count must match
#   grep -c 'zonename=".*"; *timezone_val=' <that file>
set -e
src="$1"
[ -r "$src" ] || { echo "usage: $0 <path to functions/tr098/time>" >&2; exit 1; }

cat <<'HDR'
/*
 *	This program is free software: you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation, either version 2 of the License, or
 *	(at your option) any later version.
 *
 *	City name -> (zonename, POSIX TZ) table of the product.
 *
 *	GENERATED by tools/gen-tz-table.sh, do not hand edit.
 */
#ifndef __TZ_TABLE_MTK_H
#define __TZ_TABLE_MTK_H

struct mtk_tz_entry {
	const char *city;
	const char *zonename;
	const char *tz;
};

static const struct mtk_tz_entry mtk_tz_table[] = {
HDR
sed -n 's/^[[:space:]]*"\([^"]*\)")[[:space:]]*zonename="\([^"]*\)";[[:space:]]*timezone_val="\([^"]*\)"[[:space:]]*;;.*/\t{ "\1", "\2", "\3" },/p' "$src"
cat <<'FTR'
	{ NULL, NULL, NULL }
};

#endif
FTR
