#!/bin/sh
# Write sdk/mtk/dm098/cpeagent_key_mtk.h from the product's own shell library.
#
#   ./tools/mtk-cpeagent-key.sh <TRUNK_DIR> <output header>
#
# InternetGatewayDevice.X_AIS_CPEagent.SecretKey reads back encrypted with
# the operator's AES-256 key (functions/tr098/X_AIS_CPEagent,
# encrypt_with_specialkey).  That key belongs to the product source, not to
# this one: it is taken from there at build time (feeds/libtr098 Build/Prepare)
# and the generated header is never committed.  No key found is an error --
# a build without it would read every SecretKey back as "".
set -e

[ $# -eq 2 ] || { echo "usage: $0 <TRUNK_DIR> <output header>" >&2; exit 2; }
src="$1/apps/hni/cwmpclient/ext/openwrt/scripts/functions/tr098/X_AIS_CPEagent"
[ -f "$src" ] || { echo "mtk-cpeagent-key: no $src" >&2; exit 1; }

key=$(sed -n 's/^[[:space:]]*local key_hex="\([0-9a-fA-F]*\)".*/\1/p' "$src" | head -n 1)
[ ${#key} -eq 64 ] || { echo "mtk-cpeagent-key: no 64-digit key_hex in $src" >&2; exit 1; }

tmp="$2.tmp"
{
	echo "/* GENERATED by tools/mtk-cpeagent-key.sh from the product's X_AIS_CPEagent."
	echo " * Not part of the source: do not commit. */"
	echo "#define MTK_CPEAGENT_KEY_HEX \"$key\""
} > "$tmp"
mv "$tmp" "$2"
