# GENERATED by tools/sdk-scan.sh -- do not edit.
# One entry per directory under sdk/ that carries sdk.m4 and sdk.mk.
# m4_included by configure.ac, which knows no SDK name at all.

m4_define([SDK_LIST], [bdk mtk uci])
m4_define([SDK_DEFAULT], [uci])

# with_sdk co the da duoc configure.ac dat truoc (alias cu): khong xoa no
AC_ARG_WITH([sdk],
  [AS_HELP_STRING([--with-sdk=NAME], [SDK backend, one of: bdk mtk uci (default uci)])],
  [with_sdk=$withval], [])
# --with-platform is the name this option had before the sdk/ layout; kept so
# existing build scripts (BDK Makefile, OpenWrt feed) keep working.
AC_ARG_WITH([platform],
  [AS_HELP_STRING([--with-platform=NAME], [deprecated alias of --with-sdk])],
  [test -z "$with_sdk" && with_sdk=$withval], [])
AS_IF([test -z "$with_sdk"], [with_sdk=uci])
AC_MSG_CHECKING([SDK backend])
AC_MSG_RESULT([$with_sdk])
SDK_NAME=$with_sdk
AC_SUBST([SDK_NAME])

# Every fragment is included unconditionally and guards itself on $with_sdk:
# an AM_CONDITIONAL must be reached on every configure run or config.status
# refuses to substitute it.
m4_include([sdk/bdk/sdk.m4])
m4_include([sdk/mtk/sdk.m4])
m4_include([sdk/uci/sdk.m4])

AS_CASE([$with_sdk],
  [bdk], [],
  [mtk], [],
  [uci], [],
  [AC_MSG_ERROR([unknown --with-sdk=$with_sdk, this tree has: bdk mtk uci])])
