/*
 *	This program is free software: you can redistribute it and/or modify
 *	it under the terms of the GNU General Public License as published by
 *	the Free Software Foundation, either version 2 of the License, or
 *	(at your option) any later version.
 *
 *	City name -> (zonename, POSIX TZ) table of the product.
 *
 *	GENERATED, do not hand edit.  It is the set_timezone_name() case list of
 *	the product's easycwmp function library, verbatim:
 *	  cwmpclient/ext/openwrt/scripts/functions/tr098/time
 *	Regenerate with tools/gen-tz-table.sh <that file> > tz_table_mtk.h after
 *	the product adds a city, otherwise the ACS gets 9007 for it.
 *
 *	Time.LocalTimeZoneName is the city ("Bangkok"), zonename is what goes to
 *	system.@system[0].zonename and tz to system.@system[0].timezone.
 */
#ifndef __TZ_TABLE_MTK_H
#define __TZ_TABLE_MTK_H

struct mtk_tz_entry {
	const char *city;
	const char *zonename;
	const char *tz;
};

static const struct mtk_tz_entry mtk_tz_table[] = {
	{ "Kwajalein", "Pacific/Kwajalein", "<-12>12" },
	{ "Niue", "Pacific/Niue", "<+11>11" },
	{ "Midway", "Pacific/Midway", "<+11>11" },
	{ "Apia", "Pacific/Apia", "<+11>-11<+12>,M9.5.0/3,M4.1.0/4" },
	{ "Rarotonga", "Pacific/Rarotonga", "<+10>10" },
	{ "Adak", "America/Adak", "HST10HDT,M3.2.0,M11.1.0" },
	{ "Honolulu", "Pacific/Honolulu", "HST10" },
	{ "Tahiti", "Pacific/Tahiti", "<+10>10" },
	{ "Fakaofo", "Pacific/Fakaofo", "<+10>10" },
	{ "Marquesas", "Pacific/Marquesas", "<+0930>9:30" },
	{ "Anchorage", "America/Anchorage", "AKST9AKDT,M3.2.0,M11.1.0" },
	{ "Gambier", "Pacific/Gambier", "<+09>9" },
	{ "Pitcairn", "Pacific/Pitcairn", "<+08>8" },
	{ "Dawson", "America/Dawson", "PST8PDT,M3.2.0,M11.1.0" },
	{ "Santa_Isabel", "Pacific/Guadalcanal", "<-11>11" },
	{ "Dawson_Creek", "America/Dawson_Creek", "MST7" },
	{ "Boise", "America/Boise", "MST7MDT,M3.2.0,M11.1.0" },
	{ "Chihuahua", "America/Chihuahua", "MST7MDT,M4.1.0,M10.5.0" },
	{ "Belize", "America/Belize", "CST6" },
	{ "Chicago", "America/Chicago", "CST6CDT,M3.2.0,M11.1.0" },
	{ "Cancun", "America/Cancun", "EST5" },
	{ "Galapagos", "Pacific/Galapagos", "GALT6" },
	{ "Bogota", "America/Bogota", "<-05>5" },
	{ "Havana", "America/Havana", "CST5CDT,M3.2.0,M11.1.0" },
	{ "Guayaquil", "America/Guayaquil", "<-05>5" },
	{ "Atikokan", "America/Atikokan", "EST5" },
	{ "Detroit", "America/Detroit", "EST5EDT,M3.2.0,M11.1.0" },
	{ "New_York", "America/New_York", "EST5EDT,M3.2.0,M11.1.0" },
	{ "Lima", "America/Lima", "<-05>5" },
	{ "Caracas", "America/Caracas", "<-0430>4:30" },
	{ "Boa_Vista", "America/Boa_Vista", "<-04>4" },
	{ "Campo_Grande", "America/Campo_Grande", "<-04>4<-03>,M10.3.0/0,M2.3.0/0" },
	{ "Anguilla", "America/Anguilla", "AST4" },
	{ "Glace_Bay", "America/Glace_Bay", "AST4ADT,M3.2.0,M11.1.0" },
	{ "Goose_Bay", "America/Goose_Bay", "AST4ADT,M3.2.0,M11.1.0" },
	{ "La_Paz", "America/La_Paz", "<-04>4" },
	{ "Stanley", "Atlantic/Stanley", "<-03>3" },
	{ "Guyana", "America/Guyana", "<-04>4" },
	{ "Asuncion", "America/Asuncion", "<-04>4<-03>,M10.1.0/0,M3.4.0/0" },
	{ "St_Johns", "America/St_Johns", "NST3:30NDT,M3.2.0,M11.1.0" },
	{ "Buenos_Aires", "America/Argentina/Buenos_Aires", "<-03>3" },
	{ "Araguaina", "America/Araguaina", "<-03>3" },
	{ "Sao_Paulo", "America/Sao_Paulo", "<-03>3<-02>,M10.3.0/0,M2.3.0/0" },
	{ "Cayenne", "America/Cayenne", "<-03>3" },
	{ "Miquelon", "America/Miquelon", "<-03>3<-02>,M3.2.0,M11.1.0" },
	{ "Rothera", "Antarctica/Rothera", "<-03>3" },
	{ "Paramaribo", "America/Paramaribo", "<-03>3" },
	{ "Montevideo", "America/Montevideo", "<-03>3" },
	{ "Noronha", "America/Noronha", "<-02>2" },
	{ "South_Georgia", "Atlantic/South_Georgia", "<-02>2" },
	{ "Azores", "Atlantic/Azores", "AZOST1AZODT,M3.5.0/0,M10.5.0/1" },
	{ "Cape_Verde", "Atlantic/Cape_Verde", "<-01>1" },
	{ "Scoresbysund", "America/Scoresbysund", "EGT1EGST,M3.5.0/0,M10.5.0/1" },
	{ "Abidjan", "Africa/Abidjan", "GMT0" },
	{ "Guernsey", "Europe/Guernsey", "GMT0BST,M3.5.0/1,M10.5.0" },
	{ "London", "Europe/London", "GMT0BST,M3.5.0/1,M10.5.0" },
	{ "Dublin", "Europe/Dublin", "GMT0IST,M3.5.0/1,M10.5.0" },
	{ "Casablanca", "Africa/Casablanca", "<+00>0<+01>,M3.2.0,M4.3.0" },
	{ "Canary", "Atlantic/Canary", "WET0WEST,M3.5.0/1,M10.5.0/2" },
	{ "Algiers", "Africa/Algiers", "<+01>-1" },
	{ "Ceuta", "Africa/Ceuta", "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ "Paris", "Europe/Paris", "CET-1CEST,M3.5.0,M10.5.0/3" },
	{ "Bangui", "Africa/Bangui", "<+01>-1" },
	{ "Windhoek", "Africa/Windhoek", "<+02>-2" },
	{ "Blantyre", "Africa/Blantyre", "<+02>-2" },
	{ "Tripoli", "Africa/Tripoli", "EET-2" },
	{ "Kaliningrad", "Europe/Kaliningrad", "EET-2" },
	{ "Beirut", "Asia/Beirut", "EET-2EEST,M3.5.0/0,M10.5.0/1" },
	{ "Nicosia", "Asia/Nicosia", "EET-2EEST,M3.5.0/3,M10.5.0/4" },
	{ "Gaza", "Asia/Gaza", "EET-2EEST,M3.5.0,M10.5.0" },
	{ "Damascus", "Asia/Damascus", "EET-2EEST,M3.5.0,M10.5.0" },
	{ "Johannesburg", "Africa/Johannesburg", "SAST-2" },
	{ "Aden", "Asia/Aden", "<+03>-3" },
	{ "Addis_Ababa", "Africa/Addis_Ababa", "<+03>-3" },
	{ "Samara", "Europe/Samara", "SAMT-4" },
	{ "Syowa", "Antarctica/Syowa", "<+03>-3" },
	{ "Volgograd", "Europe/Volgograd", "MSK-3" },
	{ "Tehran", "Asia/Tehran", "<+0330>-3:30<+0430>,J79/24,J263/24" },
	{ "Yerevan", "Asia/Yerevan", "<+04>-4" },
	{ "Baku", "Asia/Baku", "<+04>-4" },
	{ "Tbilisi", "Asia/Tbilisi", "<+04>-4" },
	{ "Dubai", "Asia/Dubai", "<+04>-4" },
	{ "Moscow", "Europe/Moscow", "MSK-3" },
	{ "Mauritius", "Indian/Mauritius", "<+04>-4" },
	{ "Reunion", "Indian/Reunion", "<+04>-4" },
	{ "Mahe", "Indian/Mahe", "<+04>-4" },
	{ "Kabul", "Asia/Kabul", "<+0430>-4:30" },
	{ "Aqtau", "Asia/Aqtau", "<+05>-5" },
	{ "Mawson", "Antarctica/Mawson", "<+05>-5" },
	{ "Maldives", "Indian/Maldives", "<+05>-5" },
	{ "Oral", "Asia/Oral", "<+05>-5" },
	{ "Karachi", "Asia/Karachi", "PKT-5" },
	{ "Kerguelen", "Indian/Kerguelen", "<+05>-5" },
	{ "Dushanbe", "Asia/Dushanbe", "<+05>-5" },
	{ "Ashgabat", "Asia/Ashgabat", "<+05>-5" },
	{ "Samarkand", "Asia/Samarkand", "<+05>-5" },
	{ "Yekaterinburg", "Asia/Yekaterinburg", "YEKT-5" },
	{ "Colombo", "Asia/Colombo", "<+0530>-5:30" },
	{ "Kathmandu", "Asia/Kathmandu", "<+0545>-5:45" },
	{ "Almaty", "Asia/Almaty", "<+06>-6" },
	{ "Dhaka", "Asia/Dhaka", "<+06>-6" },
	{ "Thimphu", "Asia/Thimphu", "<+06>-6" },
	{ "Chagos", "Indian/Chagos", "<+06>-6" },
	{ "Bishkek", "Asia/Bishkek", "<+06>-6" },
	{ "Novokuznetsk", "Asia/Novokuznetsk", "NOVT-7" },
	{ "Qyzylorda", "Asia/Qyzylorda", "<+06>-6" },
	{ "Vostok", "Antarctica/Vostok", "<+06>-6" },
	{ "Cocos", "Indian/Cocos", "<+0630>-6:30" },
	{ "Rangoon", "Asia/Yangon", "<+0630>-6:30" },
	{ "Christmas", "Indian/Christmas", "<+07>-7" },
	{ "Davis", "Antarctica/Davis", "<+07>-7" },
	{ "Hovd", "Asia/Hovd", "<+07>-7<+08>,M3.5.6,M9.5.6/0" },
	{ "Bangkok", "Asia/Bangkok", "<+07>-7" },
	{ "Krasnoyarsk", "Asia/Krasnoyarsk", "KRAT-7" },
	{ "Omsk", "Asia/Omsk", "OMST-6" },
	{ "Jakarta", "Asia/Jakarta", "WIB-7" },
	{ "Brunei", "Asia/Brunei", "<+08>-8" },
	{ "Choibalsan", "Asia/Choibalsan", "<+08>-8<+09>,M3.5.6,M9.5.6/0" },
	{ "Makassar", "Asia/Makassar", "WITA-8" },
	{ "Chongqing", "Asia/Chongqing", "CST-8" },
	{ "Hong_Kong", "Asia/Hong_Kong", "HKT-8" },
	{ "Irkutsk", "Asia/Irkutsk", "IRKT-8" },
	{ "Kuala_Lumpur", "Asia/Kuala_Lumpur", "<+08>-8" },
	{ "Manila", "Asia/Manila", "PHT-8" },
	{ "Singapore", "Asia/Singapore", "<+08>-8" },
	{ "Ulaanbaatar", "Asia/Ulaanbaatar", "<+08>-8<+09>,M3.5.6,M9.5.6/0" },
	{ "Casey", "Antarctica/Casey", "<+11>-11" },
	{ "Eucla", "Australia/Eucla", "<+0845>-8:45" },
	{ "Jayapura", "Asia/Jayapura", "WIT-9" },
	{ "Tokyo", "Asia/Tokyo", "JST-9" },
	{ "Seoul", "Asia/Seoul", "KST-9" },
	{ "Palau", "Pacific/Palau", "<+09>-9" },
	{ "Dili", "Asia/Dili", "<+09>-9" },
	{ "Yakutsk", "Asia/Yakutsk", "YAKT-9" },
	{ "Darwin", "Australia/Darwin", "ACST-9:30" },
	{ "Adelaide", "Australia/Adelaide", "ACST-9:30ACDT,M10.1.0,M4.1.0/3" },
	{ "Guam", "Pacific/Guam", "ChST-10" },
	{ "DumontDUrville", "Antarctica/DumontDUrville", "<+10>-10" },
	{ "Brisbane", "Australia/Brisbane", "AEST-10" },
	{ "Currie", "Australia/Currie", "AEST-10AEDT,M10.1.0,M4.1.0/3" },
	{ "Port_Moresby", "Pacific/Port_Moresby", "<+10>-10" },
	{ "Sakhalin", "Asia/Sakhalin", "<+11>-11" },
	{ "Truk", "Pacific/Chuuk", "<+10>-10" },
	{ "Vladivostok", "Asia/Vladivostok", "VLAT-10" },
	{ "Lord_Howe", "Australia/Lord_Howe", "<+1030>-10:30<+11>,M10.1.0,M4.1.0" },
	{ "Anadyr", "Asia/Anadyr", "<+12>-12" },
	{ "Kosrae", "Pacific/Kosrae", "<+11>-11" },
	{ "Magadan", "Asia/Magadan", "MAGT-11" },
	{ "Macquarie", "Antarctica/Macquarie", "<+11>-11" },
	{ "Noumea", "Pacific/Noumea", "<+11>-11" },
	{ "Kamchatka", "Asia/Kamchatka", "PETT-12" },
	{ "Ponape", "Pacific/Pohnpei", "<+11>-11" },
	{ "Guadalcanal", "Pacific/Guadalcanal", "<+11>-11" },
	{ "Efate", "Pacific/Efate", "<+11>-11" },
	{ "Norfolk", "Pacific/Norfolk", "<+11>-11<+12>,M10.1.0,M4.1.0/3" },
	{ "Fiji", "Pacific/Fiji", "<+12>-12" },
	{ "Tarawa", "Pacific/Tarawa", "<+12>-12" },
	{ "Nauru", "Pacific/Nauru", "<+12>-12" },
	{ "McMurdo", "Antarctica/McMurdo", "NZST-12NZDT,M9.5.0,M4.1.0/3" },
	{ "Funafuti", "Pacific/Funafuti", "<+12>-12" },
	{ "Wake", "Pacific/Wake", "<+12>-12" },
	{ "Wallis", "Pacific/Wallis", "<+12>-12" },
	{ "Chatham", "Pacific/Chatham", "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45" },
	{ "Enderbury", "Pacific/Enderbury", "<+13>-13" },
	{ "Tongatapu", "Pacific/Tongatapu", "<+13>-13" },
	{ "Kiritimati", "Pacific/Kiritimati", "<+14>-14" },
	{ "UTC", "UTC", "UTC" },
	{ NULL, NULL, NULL }
};

#endif
